spring.application.name=ctos-ekyc

server.port = 8091

# CTOS Config
ctos.url=https://uat-eonboarding.ctos.com.my
ctos.api.url = https://uat-eonboardinga.ctos.com.my
ctos.api-version=v2
ctos.api-key=TZq4A9blSW2ihv-MOpZ_P6OZlTZaLkwR
ctos.package-name=com.sunlife.uat.gw
ctos.iv=MTIzNDU2Nzg5MDEy
ctos.md5=m4X12dM8GeYGYl1gLXO8PaZTERGG9bVt

ctos.v3.api-version=v3
ctos.v3.api-key=rMA57BckC6wkYmLw_-UU5zQf_RlE7a0A
ctos.v3.package-name=com.sunlife.uat.api
ctos.v3.encodeKey=m4X12dM8GeYGYl1gLXO8PaZTERGG9bVt

